ALTER TABLE users ADD COLUMN IF NOT EXISTS token_version INTEGER NOT NULL DEFAULT 0;
ALTER TABLE email_otps ADD COLUMN IF NOT EXISTS purpose VARCHAR(50) NOT NULL DEFAULT 'EMAIL_VERIFY';
ALTER TABLE email_otps ADD COLUMN IF NOT EXISTS attempt_count INTEGER NOT NULL DEFAULT 0;
